### ISSUE TITLE
Missing openssl

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr-devops#123]
I see openssl-dev in docker file but module openssl is not loading on run. Is there a reason openssl-dev is used? 
edit: did notice openssl in apk add but it is not loading on start.

**Comment by jesdynf** [comment]
5.0.1 uses php7-openssl already, it looks like -- I'm betting openssl and openssl-dev are in there for the use of Let's Encrypt. Are you saying we need to add php7-openssl to the 5.0.0 Dockerfile too?

**Comment by sjpadgett** [comment]
Guess I should have looked in 5.0.1, may have saved me some time. Oh well, i'll be perfect tomorrow :). I'm not 100% for need on v5.0.0 because I upgraded from docker package for v5.0.0 to v5.0.1 in place. I just don't recall that Newcrop ever needed openssl extension. Maybe Brady knows. I'd leave for now and I will close this and the note here will allow documentation of my boo boo.

**Comment by bradymiller** [comment]
to provide background, the php7-openssl was added in 5.0.1 since mcrypt was no longer supported in php 7.2, so converted codebase from using mcrypt to openssl (and need this mu2 item to have option to encrypt log comments and also allow download of encrypted documents; i wasn't aware of newcrop need for php7-openssl).

**Comment by sjpadgett** [comment]
Probably for the logs but appears to be working now I added the php extension. Thanks guys.
