### ISSUE TITLE
Should add an env to automatically run db upgrade scripts

### ISSUE THREAD

**Issue by TheToolbox** [openemr/openemr-devops#131]
Like it says on the tin, it would likely be valuable to allow an environment variable to be supplied on container start in the event of a migration (e.g. 5.0.0 -> 5.0.1) so that a manual process isn't needed and it can be as simple as switching the version in `docker-compose.yml`.

**Comment by TheToolbox** [comment]
@jesdynf you seem to have the container upgrade path down. Is there anything beyond convincing it to run the upgrade php script?

**Comment by bradymiller** [comment]
Regarding why things are getting deleted. In the script, auto_setup is not run, and this code block gets run since sql_cong.php config var is 1 from shared volume and the auto_configure.php script exists since this is the first time the docker is run:
https://github.com/openemr/openemr-devops/blob/master/docker/openemr/5.0.1/autoconfig.sh#L97-L129

**Comment by jesdynf** [comment]
@bradymiller We're detecting and doing this now, right?

**Comment by bradymiller** [comment]
yep, this is in place now.
