### ISSUE TITLE
Ensure the permission in 5.0.1 work when upgrade to 5.0.2

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr-devops#189]
For 5.0.2, we needed to add the following:
https://github.com/openemr/openemr-devops/blob/master/docker/openemr/5.0.2/Dockerfile#L13-L14

We need to ensure that this is dealt with during the upgrade process from 5.0.1 to 5.0.2:
https://github.com/openemr/openemr-devops/blob/master/packages/lightsail/upgrade.md

**Comment by danehrlich1** [comment]
I will look into this. Some interesting facts btw:

The version of Apache available in the Debian and Ubuntu repos is TERRIBLE. 2.4.25 and 2.4.29 respectively. 

For whatever reason, Alpine Linux has 2.4.34, which is pretty new (latest is 2.4.38).

Anyway if you are ever looking at Apache docs, Alpine Linux will usually be 100% compatible, but be careful. If you are on Ubuntu or Debian...be super careful.

Anyway will check this out because interested in this / how user permissions effect things.

**Comment by bradymiller** [comment]
Completed this here:
https://github.com/openemr/openemr-devops/pull/200

Now can do complete upgrade (both codebase and database) by simply updating docker image in docker-compose.yml (5.0.1 to 5.0.2) as long as the sites/ directory is a shared volume (and not sharing the entire openemr codebase on a shared volume for obvious reasons).

Also straightforward to support version upgrades in the future:
https://www.open-emr.org/wiki/index.php/Steps_for_an_official_release#7._Prepare_for_docker_upgrade

**Comment by bradymiller** [comment]
New upgrade doc is here:
https://github.com/openemr/openemr-devops/pull/201
