### ISSUE TITLE
on-demand client certs

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr-devops#262]
Something that would be really neat in the docker setup (which supports self-signed key automatically and lets encrypt if set it up) would be 2 functions inside the docker (kind of like devtools for developers, but instead prodtools functions for production use) that an admin can run outside the docker that does:
1. Configures (and unconfigures) apache to use client based certs (ie. lock it down so only access with the client based certs)
2. Spits out a client based cert for a user

**Comment by jesdynf** [comment]
This is just... I can't even figure out how I might do it. I guess I'd...

 * Rename ssl.conf to ssl.stock.conf and link to it from conf.d.
 * Provide ssl.clientcerts.conf which duplicates ssl.conf except it includes the client stanzas. 
 * Provide replacement openemr.clientcerts.conf which locks out :80 entirely.
 * Provide a script which generates a CA and swaps in the client cert configs.
 * Provide a script which reverses this decision.
 * Provide a script that will spit out a signed client cert.

Could be done, although it'd be a huge hassle and completely antithetical to any kind of multinode deployment... unless you just provided a front-end nginx that had that scripting and then loadbalanced requests to a cluster behind it, which would take the client cert stuff /out/ of the OE nodes and would honestly be a huge relative win.

**Comment by jesdynf** [comment]
You know what, when I look at it as a question of multinode I immediately want to throw the whole thing out after all and I think that's the right decision. I think we'd be *way* better served just adding an nginx container to the mix, doing our cert stuff on *it*, and then reverse-proxying to OpenEMR container(s) instead of keeping a valid CA signing cert on every swarm node which is about what I'd have to do for this to work.

https://fardog.io/blog/2017/12/30/client-side-certificate-authentication-with-nginx/
