### ISSUE TITLE
Remove SSL from Docker image

### ISSUE THREAD

**Issue by aebrahim** [openemr/openemr-devops#335]
### Describe the problem

I am trying to deploy this service into cloud run in GCP and put it behind a load balancer, and the SSL is getting in the way.

### Describe the solution you'd like

The more idiomatic approach would be to remove the SSL state from the main Docker image. For a working kubernetes or docker-compose deployment with SSL, a second container should be run that can reverse-proxy requests to openemr and apply SSL. This way is the most flexible, because it makes it very easy to swap out whatever SSL method the deployer wants - for example, I can simply use my load balancer.

**Comment by jesdynf** [comment]
Hi, Ali.

I understand where you're coming from, but that would be a significant breaking change -- if we remove SSL as you describe in the next version of the container, any existing docker-compose builds that pull in an updated image will fail. (When we originally made the container, we didn't find adding SSL a hardship since OpenEMR already required a webserver to serve PHP.) I would instead recommend you roll your own image -- you're already in the right place to do so.

 * Review https://github.com/openemr/openemr-devops/tree/master/docker/openemr/7.0.0 for the current Docker build structure.
  * Modify `openemr.sh` to remove the call to `ssl.sh`.
  * Modify `openemr.conf` to remove the SSL verbiage (and add whatever header changes you prefer to a container devoted to being reverse proxied.)
  * Build the container, tag it, and push it to your personal container repo.

Since this devops repo *pulls in* the contents of the tagged OpenEMR release branch, the upkeep of your personal container should be very modest -- when a security update or patch release is announced, review this single 7.0.0 path for updates (of which I expect there to be none) and rebuild your image. The `rel-700` tag marker will have already been moved to the right release and everything should Just Magically Work.

I hope this helps!

**Comment by bradymiller** [comment]
Can't ssl port 443 just be ignored (i.e just use port 80 via http in the docker for cases where encryption/ssl is done upstream) ?

**Comment by aebrahim** [comment]
The issue is more that it's another instance of container state where we store the certificate, and additional jobs for the letsencrypt updater.

While kubernetes allows both, ideally in docker I would think we would want to minimize both of these to improve reliability and performance.

For example, both of these issues prevent running this image in cloud run on Google Cloud (I thought it would be really nice in terms of management ease to have a serverless solution backed by managed SQL and Redis instances and deployed with a few dozen lines of terraform). There would still be the issue of the SQL configuration state being stored in the container, but that's harder to solve. Removing SSL seems like a much easier thing to fix first, and would also improve reliability.

**Comment by aebrahim** [comment]
Thanks for the advice though, it's similar to what I've been trying.

If I get it working I'll try to post my results back here!
