### ISSUE TITLE
OpenEMR look at using php-fpm's memory cache layer to cache the sqlconf database credentials

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr-devops#381]
Talking with @jesdynf we were discussing how kubernetes clusters have often been bottlenecked at the filesystem layer by having to retrieve the sqlconf.php file on every request in order to open a database connection.  We discussed investigating php-fpm's shared memory operations to be able to cache the sqlconf.php and avoid the contention issue that happens on the filesystem for this.  Just putting this issue up to help me remember and for us to look into it.

Relevant files to look at are here:
https://github.com/openemr/openemr-devops/blob/master/docker/openemr/7.0.3/Dockerfile

Also we should investigate php's Shmop extension as well as ACPU.  I don't believe our current opcache lets us store objects in the opcache.
https://www.php.net/manual/en/book.shmop.php

Note one of the things we'll need to make sure of is how to handle the security aspects of the shared memory as this introduces a new threat vector that has to be analyzed in our risk assessment.

**Comment by jesdynf** [comment]
You know, *has* anybody tried to cluster this since the opcache stuff went in? Has anyone stood up and said they're still getting contention on sqlconf that opcache didn't fix? I don't see any reason to think it's not working like it should or being excluded.

**Comment by adunsulag** [comment]
@jesdynf I have not done any testing since the opcache went in and perhaps that has resolved the issue.

**Comment by jesdynf** [comment]
I've gone through opcache in general and how we're using it in particular -- it gets turned on by default, it gets turned off if the JIT debugger is running, and the initial setup uses it in a slightly idiosyncratic way for reasons that aren't clear to me but don't matter because it's only during setup.

As near as I can tell we should be fine as we are. I don't think there will be any general support for longer delays between fs timestamp checks but that's the only way we could reduce contention further -- were it still an issue at all. There aren't fine-grained controls to allow-list a given template (just deny-list) or force it to have even longer cache times.

**Comment by jesdynf** [comment]
Testing from Jacob Mevorach suggests opcache is definitely working like it's supposed to, so I'm going to go ahead and close this out.
