### ISSUE TITLE
EULA

### ISSUE THREAD

**Issue by robertdown** [openemr/openemr-devops#43]

**Comment by johnbwilliams** [comment]
- **Proposed EULA for OpenEMR Cloud services on AWS:** @robert.down Hi
   Robert. This EULA is good enough for initial release. I have an inquiry
   into AAWS legal re addition language - we can always up date it after
   initial listing
   -
   1. Your use of OpenEMR software on AWS is governed by the terms of the
   AWS Customer Agreement (https://aws.amazon.com/agreement) or other
   agreement with AWS governing your use of AWS services.
   2. OpenEMR software comes with no guarantees or warranties of any sorts,
   either written or implied.
   3. OpenEMR sofware is released as General GNU Public Licence (GNU GPL 3)
   (https://www.gnu.org/licenses/gpl-3.0.en.html)
   4. OpenEMR SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS''
   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
   ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR
   ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
   DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
   SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
   CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
   LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
   OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
   DAMAGE.
   5. THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY
   APPLICABLE LAW. EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT
   HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM “AS IS” WITHOUT WARRANTY
   OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,
   THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
   PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM
   IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL
   NECESSARY SERVICING, REPAIR OR CORRECTION.
   6. IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING
   WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS
   THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY
   GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE
   USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF
   DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD
   PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS),
   EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF
   SUCH DAMAGES.
   7. If the disclaimer of warranty and limitation of liability provided
   above cannot be given local legal effect according to their terms,
   reviewing courts shall apply local law that most closely approximates an
   absolute waiver of all civil liability in connection with the Program,
   unless a warranty or assumption of liability accompanies a copy of the
   Program in return for a fee.

   <https://aws.amazon.com/agreement/>
   aws.amazon.com

**Comment by robertdown** [comment]
### [Status: PROPOSAL]

# EULA for OpenEMR Cloud services on AWS

1. Your use of OpenEMR software on AWS is governed by the terms of the AWS 
Customer Agreement (https://aws.amazon.com/agreement) or other agreement with 
AWS governing your use of AWS services.
2. OpenEMR software comes with no guarantees or warranties of any sorts, either 
written or implied.
3. OpenEMR sofware is released as General GNU Public Licence (GNU GPL3) 
(https://www.gnu.org/licenses/gpl-3.0.en.html)
4. OpenEMR SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY 
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON 
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
5. THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE 
LAW. EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER 
PARTIES PROVIDE THE PROGRAM “AS IS” WITHOUT WARRANTY OF ANY KIND, EITHER 
EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS TO THE 
QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE 
DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.
6. IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING WILL 
ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS THE PROGRAM
AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, 
SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY
TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING 
RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A FAILURE OF 
THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH HOLDER OR OTHER 
PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
7. If the disclaimer of warranty and limitation of liability provided above 
cannot be given local legal effect according to their terms, reviewing courts 
shall apply local law that most closely approximates an absolute waiver of all 
civil liability in connection with the Program, unless a warranty or assumption 
of liability accompanies a copy of the Program in return for a fee. 
https://aws.amazon.com/agreement

**Comment by johnbwilliams** [comment]
Have inquiry into AWS legal re add'l language for this EULA   Not necessary for initial product listing, IMO, can always update after listing.  If product is successful, at some we'll want to invest in professional legal service to write a much better EULA.  This one is "good enough" IMO, for initial product listing on AWS Marketplace.

**Comment by sunsetsystems** [comment]
What's the original source for this? Since (I presume) none of us are lawyers we're effectively depending on that for legal advice.

**Comment by johnbwilliams** [comment]
It was crafted from the EULA's of several open source software-based
services on AWS Marketplace  (which vary widely).  Most  of the language is
a direct lift from the GPL itself

**Comment by MatthewVita** [comment]
@robertdown LGTM

**Comment by sunsetsystems** [comment]
Thanks. Two minor corrections.
o In paragraph 2 change "sorts" to "sort".
o In paragraph 3 change "as" to "pursuant to".

**Comment by jesdynf** [comment]
I brought in the PR from Rod and Stephen. Has this issue been met, or does more need to be done?
